[package]
name = "toy-zkvm"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
thiserror = "2.0.17"
rand = "0.9.0"
ark-bn254 = "0.5.0"
ark-poly = "0.5.0"
ark-std = "0.5.0"
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
